### PR TITLE
Catch exceptions replacestate pushstate

### PR DESCRIPTION
**Pull request by SabatinoMasala**
Follow-up of https://github.com/inertiajs/inertia/issues/109

Added 2 exception handlers on both `replaceState` and `pushState` with a small warning, to help the developer troubleshoot potential issues.

### CODE REVIEW

**Comment by SamJakob** [comment]
Can this PR be considered for merge?

**Comment by briannastatic** [comment]
Same. Also looking for this to be merged.

**Comment by claudiodekker** [comment]
Hmm.. Personally, I'm not in favour of this change. My reasons are simple:

- Most developers won't ever run into this problem
- It adds an extra maintenance burden / something to keep into account
- **Every user will end up with an increased build size**

Instead, simply by posting this comment and including `NS_ERROR_ILLEGAL_VALUE` in it like I'm doing now, this issue will show up at the very top of Google when someone runs into it. This, by itself, is already sufficient information for most developers to be able to figure out what's going on, especially given the context of the changes you're suggesting.

**Comment by reinink** [comment]
Hey folks!

So, I've been thinking about this change for a while, and while I totally get why you want to add this, I don't think it actually makes sense:

1. I don’t think it’s our job to report browser errors better. If anything this should be reported to Firefox to report on better. 
2. Hiding the original error (`NS_ERROR_ILLEGAL_VALUE`) makes this harder to Google search (if you wanted to do more search into this problem).
3. A general try/catch could hide other errors, unrelated to the size problem.

Plus, if you can already run Google search for "NS_ERROR_ILLEGAL_VALUE inertia" and find these related issues (and the solution—don't pass so much data!). Finally, I've updated the Inertia.js docs (https://github.com/inertiajs/inertiajs.com/commit/d2719574e80b44ea8964f96d705e6ef0e86fefd5) to include this cryptic error in the note we have about response sizes.

Hope that makes sense. Thanks for your contribution either way!

**Pull request closed without merging**
