### PR TITLE
[Svelte] Improve typescript types + minor fixes

### PR DESCRIPTION
**Pull request by pedroborges**
Reopening #1881 originally created by @jamesst20.

### CODE REVIEW

**Comment by jamesst20** [comment]
Hey @pedroborges 

If you ever reopen the minimal upgrade for Svelte 5, I found a bug this week where a noticed SSR is no longer working with newer build of Svelte 5 starting from next.179+.

You may want to apply this as well 

https://github.com/jamesst20/inertia/commit/c8493ab9358fb520461940ef7f043987f0b39d17

This is because Svelte 5 uses anchors (comments) and the `div I'd=app` is passed into the `render(...)` function of Svelte server and it makes anchors outside the div. So when it comes to hydrate the div it completely crash

**Comment by pedroborges** [comment]
Thanks for letting me know @jamesst20, I'll check it out. Really appreciate your work on these PRs 🙇‍♂️

**Comment by joetannenbaum** [comment]
This all looks good, thank you both for all of the work you put into this.

When I fire up the Svelte playground I'm getting a bunch of warnings in the console, I just want to make sure that they aren't a by-product of this PR. Any insight here?

CleanShot 2024-09-11 at 16 46 08@2x

**Comment by pedroborges** [comment]
> When I fire up the Svelte playground I'm getting a bunch of warnings in the console, I just want to make sure that they aren't a by-product of this PR. Any insight here?

Inertia passes all props from server to every layout and page components. Each component only declares the props it needs, these warnings are just Svelte "complaining" about that. You only see them in development. All good 👍

**Review by joetannenbaum — APPROVED** [review]
This all looks good to me, thank you both for all of your work on it!

**Pull request merged**
