### PR TITLE
Pass the full page object to resolve component

### PR DESCRIPTION
**Pull request by james-em**
See discussion #1863

### CODE REVIEW

**Comment by james-em** [comment]
May I pull your attention here? :) @reinink 

I believe it's a really quick QA without any kind of side effect and I did it for all adapters and typescript types

**Comment by reinink** [comment]
Yup, I think this makes sense! Will test this out and let you know.

**Comment by james-em** [comment]
> Yup, I think this makes sense! Will test this out and let you know.



> Yup, I think this makes sense! Will test this out and let you know.

If you merge Svelte Typescript support, I will update this PR very quickly to include new Svelte types

**Comment by jamesst20** [comment]
It appears to me the project Inertia is dead and there are no more reasons for me to keep my work open and maintain it.

I am closing all my opened PRs which includes https://github.com/inertiajs/inertia/pull/1864 https://github.com/inertiajs/inertia/pull/1872 https://github.com/inertiajs/inertia/pull/1873 https://github.com/inertiajs/inertia/pull/1874 https://github.com/inertiajs/inertia/pull/1875 https://github.com/inertiajs/inertia/pull/1881

I will be maintaining unofficially my own fork of this library so my projects using Svelte 5 can still live until I find or create an appropriate replacement for this library.

Thanks to everyone who spent time looking at my PRs.

**Comment by reinink** [comment]
> It appears to me the project Inertia is dead and there are no more reasons for me to keep my work open and maintain it.
> 
> I am closing all my opened PRs which includes #1864 #1872 #1873 #1874 #1875 #1881
> 
> I will be maintaining unofficially my own fork of this library so my projects using Svelte 5 can still live until I find or create an appropriate replacement for this library.
> 
> Thanks to everyone who spent time looking at my PRs.

Bummer dude 😕

We've been working *really* hard on Inertia.js v2.0 (as you can see in [Taylor's Laracon keynote](https://www.youtube.com/watch?v=AwWepVU5uWM)), so the project is far from dead — we're just in a bit of an awkward position between major versions.

I apologize that your work has not received more attention, that's partly my fault for not having enough time to review PRs recently. I don't work on Inertia.js full time like other open source maintainers (ie. Laravel, Livewire), so for me it actually requires time out of my personal life. Because of that things just take longer, as much as I wish it didn't.

Thanks for your contributions either way.

**Pull request closed without merging**
