### PR TITLE
Create a dist version

### PR DESCRIPTION
**Pull request by sebastiandedeyne**
Add [microbundle](https://github.com/developit/microbundle) to create a bundled version of Inertia so the dependencies get transpiled before release. This also would enable people to play around with Inertia through a service like [unkpgd](https://unpkg.com/).

Microbundle requires near-zero configuration, and since Inertia doesn't have any special bundling needs, it does the job as it should. It also works for inertia-vue and inertia-react (see inertiajs/inertia-react#40). I don't know enough about Svelte to say what that repo will need for bundling (ping @pedroborges)

Open for feedback! I'll also test drive the dist folder in some projects of mine before merging.

### CODE REVIEW

**Comment by pedroborges** [comment]
I'll test it soon and let you know how it plays with the Svelte adapter.

**Comment by adamwathan** [comment]
Just for my own curiosity, what target is this transpiled against? IE10? IE11? Evergreen only? Node 6?

Side note: I've always wondered why it even makes sense to do this because different projects have different browser support requirements, so if you transpile your npm package for IE10 but someone installing the library only needs to support Edge, they are stuck with a bunch of extra bytes they didn't actually need. Makes so much more sense to me to transpile your own dependencies but it seems that everything works this way though so 🤷‍♂

**Comment by sebastiandedeyne** [comment]
> Just for my own curiosity, what target is this transpiled against? IE10? IE11? Evergreen only? Node 6?

IE-something but I'm not sure which 😬 It uses babel-preset-env under the hood without any explicit browser config I think. Might be worth looking into what targeting more modern browsers does with the file size.

> Side note: ...

Yeah this is a tough one 😅 A few thoughts...

First of all, back in the day, not sure if this is still a thing, one of the core philosophies of npm was that a once you download a package, it should be ready to use everywhere. Because of that, packages have traditionally been transpiled to the lowest common denominator.

Secondly, and I'm also not sure if this still is relevant, Webpack + babel used to be suuuper slow, and if they also needed to transpile a few megabytes of vendor modules, build times become rediculously slow. That's why node_modules were/are generally ignored by babel, because the compilation speed has a huge effect on the developer experience.

Not relevant for Inertia, but it shouldn't be up to the consumer to know what tools your libary needs to transpile. Not a problem if you're using standard features, but if you're using non-standard features (like decorators), they defenitely should be transpiled before they enter node_modules.

Fwiw, Laravel Mix excludes node_modules: https://github.com/JeffreyWay/laravel-mix/blob/03cbfc7102a58f5d16c95c72b9b76f92c6dba8fd/src/components/JavaScript.js#L70

The current setup also adds a UMD build which can be served through a CDN. This one defenitely needs to be transpiled because it might be loaded straight into a browser.

That's all I know, but I also still have lots of questions about this stuff. This would be good stuff to hear about from an expert on a podcast 😬

**Comment by sebastiandedeyne** [comment]
Apparently Webpack is doing some crazy stuff with `.mjs` files which causes issues. For now I'm just gonna drop the module build, I don't think it's critical.

See https://github.com/developit/microbundle/issues/426

My project is correctly picking up the dist versions of `inertia` and `inertia-react` now 🎉 

However... Apparently microbundler/rollup don't support mixing default and named exports (at least not by default), which is what's happening here. Going to look into possible solutions.

**Comment by sebastiandedeyne** [comment]
I'm currently leaning towards not mixing named and default exports to remove a lot of headaches.

Right now Inertia needs to export `Inertia` (currently as `default`) and `shouldIntercept`(currently named) We have a few choices going forward

1) All named

```js
import { Inertia, shouldIntercept } from 'inertia'
```

2) Turn `shouldIntercept` into an instance method and default export `Inertia`

```js
import Inertia from 'inertia'

Inertia.shouldIntercept(...)
```

3) Multiple default exports from multiple files

```js
import Inertia from 'inertia'
import shouldIntercept from 'inertia/should-intercept
```

I'm currently leaning towards (1) or (2). Note that adapter packages will probably all change to named exports only. (2) looks cleaner, (1) would be more consistent with the adapters, although I don't think that's necessarily important since it's a different context.

**Comment by Juhlinus** [comment]
I'm leaning towards the second option as well. 

It's simple but also explicit from what I can tell.

**Comment by MichaelDeBoey** [comment]
My vote goes to all named exports here

**Comment by adamwathan** [comment]
What sort of headaches are introduced by combining default and named exports?

**Comment by reinink** [comment]
My vote at this point is all named exports. While the `shouldIntercept()` example feels better as a method maybe, I don't think it works as well for components, such as `<InertiaLink>`.

```js
import InertiaVue from 'inertia-vue'
InertiaVue.app()
InertiaVue.link()

// This is now necessary? 🤢
const Link = InertiaVue.link() 
```

Named exports just feel cleaner:

```js
import { InertiaApp, InertiaLink } from 'inertia-vue'
```

Named exports feel more predictable to me. No guessing what the default is.

And, using named exports, we can always add a default back again in the future without any breaking changes (should we find a bundling tool that makes them easier).

**Comment by adamwathan** [comment]
Good reasoning, going with all named exports sounds like the least regrettable option I think 👍🏻

**Comment by sebastiandedeyne** [comment]
From what I understand...

The problem lies with UMD, which doesn't support the idea of default exports. UMD bundles export one thing, which is either a single export (similar to a default export), or an object with multiple keys (similar to named exports). Both aren't possible, because once you have named exports you end up with something like `const Inertia = require('inertia').default`.

Some bundlers have some hacky solutions for this, but because it's all non-standard rollup and in turn microbundle don't support mixing export types.

From rollup's docs:

> It is bad practice to mix default and named exports in the same module, though it is allowed by the specification.

From a practical point of view for us as maintainers, this would mean we'd need to support a vastly more complex build configuration just to support mixed exports.

Also: TypeScript typings for mixed exports are tricky to get right too, so that's another problem that'd be solved.

**Comment by sebastiandedeyne** [comment]
Regarding default vs named, @MichaelDeBoey has already expressed a few times that from a dev experience point of view, named exports are superior.

https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad

**Comment by pedroborges** [comment]
I also like the current all named option.

**Comment by samselikoff** [comment]
First just wanted to say thanks for sharing all this info in public @sebastiandedeyne! I'm a friend of @reinink and been following along with the project. It's been interesting reading through the setup you landed on here.

I'm also working on a JS lib, and we've been fighting with the npm distribution issue as well. The library started off as an Ember project years ago, and they take care of all this rollup/transpilation setup for you, but now that we're making it a general-purpose JS lib we've had to configure different builds via rollup. Microbundle looks awesome so I'm excited to dig into it!

@adamwathan just wanted to add to the discussion about transpiling ahead of time, I think Webpack has the ability to look at a `modules` key in `package.json` to find the entry point for untranspiled modules in the source. (This would typically point to something like `src/index.js`. That lets folks consuming your library who _do_ have build pipelines set up, take advantage of the raw untraspiled source code, so their tooling can tree-shake it and target whatever browser their own app supports. I think there's also "mjs" or "esm" builds (ecmascript modules) that roll up the import statements but leave the code untranspiled for the same reason. But basically a lot of folks work on JS projects without a build tool so the lowest-common denominator build is still prevalent. One thing I'm still confused about is how this applies to `node_modules`, I think it would be too slow for even modern build setups to transpile everything they depend on in node_modules, so those are usually already transpiled. I don't know, the whole thing kinda feels like a crazy mess.

We also hit the default/named exports issue and are going all named. It also has a benefit of being easier to refactor when using TypeScript and/or VSCode. From what I gather it seems to becoming more of a trend in the frontend community.

Another thing we've struggled with is the best way to write tests, especially given our multiple builds, as well as the fact that our library works in both the browser and node (and has slightly different behavior in each environment). Our thinking right now is that we definitely want a few high-level tests that run agains the actual builds, just to cover our build config and make sure we don't break that. We're still ironing out the details here but I'm happy to share our setup any time.

Anyways, just wanted to drop some thoughts here after reading through the thread, so maybe we can help each other figure all this stuff out together! Congrats on all the progress on Inertia so far and keep it up 💪

**Comment by samselikoff** [comment]
Oh one more thing - Travis has a great npm integration which makes it easy for them to publish your package to the npm repository on new tags. So our release process happens all from the GitHub UI:

- edit `package.json` with the new version number
- go to Releases, create a new tag from latest `master`

and that's it. Travis will see the new tag, build all the dist files and then publish to npm. This is great because (1) all npm publications go through Travis and (2) anyone who gains contrib access to the GitHub repo, can now release the project.

If you're curious here's our release job: https://github.com/miragejs/server/blob/master/.travis.yml#L40

When setting up new projects I usually just follow [this guide](https://docs.travis-ci.com/user/deployment/npm/).

**Comment by reinink** [comment]
@samselikoff Awesome man! Thanks for jumping in here and sharing this info! 💪 

And yes, let figure this crap out! 😂

**Pull request merged**
