### PR TITLE
Inertia-link: Local event support

### PR DESCRIPTION
**Pull request by claudiodekker**
```vue
<InertiaLink :href="`/posts/${post.id}`" method="delete" @start="() => confirm('Are you sure you delete this post?')">
  Delete post
</InertiaLink>
```

### CODE REVIEW

**Comment by reinink** [comment]
Awesome, thanks @claudiodekker. I'd love to get this added to the React and Svelte adapters at the same time. Do you feel comfortable making that change as well? Maybe @sebastiandedeyne and @pedroborges can provide direction (or PR it themselves).

**Comment by claudiodekker** [comment]
I gave it a shot, but React & Svelte do things quite differently, and since I really don't know either I figured I'd just leave it be for the others. Sorry!

**Comment by pedroborges** [comment]
I started looking into it. I report back when I find a straight-forward way to implement it in the Svelte adapter.

**Comment by pedroborges** [comment]
What does this PR change in userland?

`<inertia-link data="{ on: click: () => { /* ... */ } }" href="/">Home</inertia-link>`

or

`<inertia-link href="/" @click="() => { /* ... */ }">Home</inertia-link>`

**Comment by claudiodekker** [comment]
There's no change in the userland part, really (so the 2nd example).

Rather, it's just that the new listeners get 'forwarded' to the underlying `Inertia.visit` call if provided (otherwise a noop method gets passed)

**Comment by pedroborges** [comment]
You answered my question. I used `@click`, should have used one of the new events...

**Pull request merged**
