### PR TITLE
Fix resolveComponent types

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Comment by reinink** [comment]
I'm just going to go ahead and assume that was correct. 😂

**Comment by MichaelDeBoey** [comment]
You either return a `Component` or a Promise that returns a `Component`, no? 🤔

**Comment by reinink** [comment]
Yep, exactly. Previously you _had_ to return a promise from the callback. Now you can just return the component straight up.

**Comment by MichaelDeBoey** [comment]
So that seems correct then the  return type 😉

**Pull request merged**
