### PR TITLE
Fix svelte 4 warning

### PR DESCRIPTION
**Pull request by punyflash**
#1627

### CODE REVIEW

**Review by jessarcher — COMMENTED** [review]
I think the warning is a false positive, and I don't think this is the right way to solve it.

Ideally, the `Link` component should always be used to render an `<a>` or `<button>`, which already comes with the correct role by default.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/link_role#best_practices

Adding the role unnecessarily seems like it's against the best practices, and interestingly it goes against the [`a11y-no-redundant-roles`](https://svelte.dev/docs/accessibility-warnings#a11y-no-redundant-roles) rule.

Ideally, the warning would be smart enough to only appear if someone chooses to render something other than an `a` or `button`; in that case, it should be on them to add the correct role for their situation. I'm not sure whether this is possible, though.

Assuming that isn't possible, this might be an appropriate case for an ignore per https://svelte.dev/docs/accessibility-warnings. E.g:

```
<!-- svelte-ignore a11y-a11y-no-static-element-interactions -->
```

**Comment by pedroborges** [comment]
I agree with @jessarcher, just using the `svelte-ignore` rule should get rid of the warning. Please update and test your PR and I'll gladly approve it.

**Comment by ingLomeland** [comment]
Whats the status on this PR? it fixes the issue with the ARIA warning on build in #1627

**Comment by driesvints** [comment]
This PR seems to have stalled as the OP isn't answering anymore. It's best that someone else picks up the work in a new PR.

**Comment by Isaac-alencar** [comment]
> This PR seems to have stalled as the OP isn't answering anymore. It's best that someone else picks up the work in a new PR.

I can take this one. I am struggling right now with this issue, so I can make the changes proposed by the original author.

**Comment by reinink** [comment]
Decided to fix this using a `svelte-ignore` as @jessarcher suggested (see #1858), and that has been released as part of [v1.0.16](https://github.com/inertiajs/inertia/releases/tag/v1.0.16) 👍

**Pull request closed without merging**
