### PR TITLE
Fix types for npm packages

### LINKED ISSUE #1793: TypeScript types are not exported properly
### Versions:

- `@inertiajs/core` version:1.0.14
- `@inertiajs/react` version: 1.0.14

### Describe the problem:

When importing types in a project with `NodeNext` as `module` and `moduleResolution` in `tsconfig.json`, the types are not being resolved properly because.

### Steps to reproduce:

```jsonc
// tsconfig.json
{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true
  }
}

```

```ts
// app.ts
import { VisitOptions } from '@inertiajs/core';
```

Error:

Screenshot 2024-02-10 at 9 29 18 PM

```
Module '"@inertiajs/core"' has no exported member 'VisitOptions'.
```

Similarly, there are other such errors for all the types when `strict` model is enabled in `tsconfig.json`

Screenshot 2024-02-10 at 9 27 48 PM

- `"Parameter 'title' implicitly has an 'any' type."`
- `"Binding element 'el' implicitly has an 'any' type."`
- `"Binding element 'App' implicitly has an 'any' type."`
- `"Binding element 'props' implicitly has an 'any' type."`
- `"Parameter 'name' implicitly has an 'any' type."`

### Reason

[arethetypeswrong](https://arethetypeswrong.github.io) correctly points out the problems with the exported types

- [`@inertiajs/core@1.0.14`](https://arethetypeswrong.github.io/?p=%40inertiajs%2Fcore%401.0.14)

<table>
    <thead>
      <tr>
        <th></th>
        <th><code>"@inertiajs/core"</code></th><th><code>"@inertiajs/core/server"</code></th>
      </tr>
    </thead>
    <tbody>
<tr>
          <td><code>node10</code></td>
          <td>✅ </td><td>✅ </td>
        </tr>
        <tr>
          <td><code>node16</code> (from CJS)</td>
          <td>⚠️ ESM (dynamic import only)<br>🚭 Unexpected module syntax<br>🥴 Internal resolution error (6)</td><td>⚠️ ESM (dynamic import only)<br>❗️ Incorrect default export<br>🚭 Unexpected module syntax<br>🥴 Internal resolution error</td>
        </tr>
        <tr>
          <td><code>node16</code> (from ESM)</td>
          <td>🥴 Internal resolution error (6)</td><td>🥴 Internal resolution error</td>
        </tr>
        <tr>
          <td><code>bundler</code></td>
          <td>✅ </td><td>✅ </td>
        </tr>
      </tbody></table>

- [`@inertiajs/react@1.0.14`](https://arethetypeswrong.github.io/?p=%40inertiajs%2Freact%401.0.14)

<table>
    <thead>
      <tr>
        <th></th>
        <th><code>"@inertiajs/react"</code></th><th><code>"@inertiajs/react/server"</code></th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><code>node10</code></td>
          <td>✅ </td><td>✅ </td>
        </tr>
        <tr>
          <td><code>node16</code> (from CJS)</td>
          <td>⚠️ ESM (dynamic import only)<br>🚭 Unexpected module syntax<br>🥴 Internal resolution error (6)</td><td>⚠️ ESM (dynamic import only)<br>❗️ Incorrect default export<br>🚭 Unexpected module syntax</td>
        </tr>
        <tr>
          <td><code>node16</code> (from ESM)</td>
          <td>🥴 Internal resolution error (6)</td><td>✅ (ESM)</td>
        </tr>
        <tr>
          <td><code>bundler</code></td>
          <td>✅ </td><td>✅ </td>
        </tr>
      </tbody></table>

### PR DESCRIPTION
**Pull request by irshadahmad21**
Fixes #1793 #1770

This PR:

- Changes the build tool from ESBuild to Tsup
- Ensures that correct types are produced on build
- Fixes the exports in package.json for all the TS packages

Using the [arethetypeswrong](https://arethetypeswrong.github.io/) CLI, here are the before and after results

<table>
    <thead>
        <tr>
            <th>BEFORE</th>
            <th>AFTER</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th colspan="2"><code>@inertiajs/core</code></th>
        </tr>
        <tr>
            <td>Screenshot 2024-02-10 at 9 47 32 PM</td>
            <td>Screenshot 2024-02-10 at 9 52 06 PM
            </td>
        </tr>
        <tr>
            <th colspan="2"><code>@inertiajs/react</code></th>
        </tr>
        <tr>
            <td>Screenshot 2024-02-10 at 9 47 57 PM</td>
            <td>Screenshot 2024-02-10 at 9 52 20 PM
                </td>
        </tr>
        <tr>
            <th colspan="2"><code>@inertiajs/vue2</code></th>
        </tr>
        <tr>
            <td>Screenshot 2024-02-10 at 9 48 17 PM</td>
            <td>Screenshot 2024-02-10 at 9 52 32 PM
                </td>
        </tr>
        <tr>
            <th colspan="2"><code>@inertiajs/vue3</code></th>
        </tr>
        <tr>
            <td>Screenshot 2024-02-10 at 9 48 34 PM</td>
            <td>Screenshot 2024-02-10 at 9 52 45 PM</td>
        </tr>
    </tbody>
</table>

### Next steps
- Update `typescript` and `@types/react*` to the latest version
- Get rid of a few `// @ts-expect-error` comments

### CODE REVIEW

**Comment by irshadahmad21** [comment]
It's getting difficult to work with Inertia with broken types. Lots of TS errors and broken auto-completions on modern TS stack.

Can we please have a look at this and ship it as soon as we can?

CC: @reinink @claudiodekker @jessarcher

**Comment by irshadahmad21** [comment]
Had to rebase to resolve conflicts in lockfile

**Comment by adiramardiani** [comment]
Up for better typescript experience

**Comment by irshadahmad21** [comment]
@reinink @claudiodekker @jessarcher

Is there any possibility of this landing anytime soon?

**Comment by jrson83** [comment]
@irshadahmad21 could you please contact me on the inertia discord `jrson83` or by mail `just@jrson.me`.

**Comment by reinink** [comment]
@irshadahmad21 Hey definitely not trying to ignore, we've actually been busy lately trying to get on top of issues (thanks a bunch to @driesvints for all his help here), and we've actually talked about this PR internally. This project has a lot of moving parts and so we need to be careful when making changes, plus I work on this project in my free time, so things often take months, not weeks or days. Honestly doing my best 😕

I also don't know much about tsup, but I am familiar with ESBuild, so making this change required me to do some homework first before changing a key part of our tooling.

**Comment by irshadahmad21** [comment]
Coming back after so many months to give Intertia another chance, but it still sucks with TypeScript, even after v2.

**Pull request closed without merging**
