### PR TITLE
Change Vue3 adapter to reactive

### PR DESCRIPTION
**Pull request by ajnsn**
A little "addon" to #440. I noticed that the Vue3 adapter is also using `ref()` for non-primitive values.

This PR changes to a reactive `current` object. This should be also more comparable what the React adapter does with `useState()`.

### CODE REVIEW

**Comment by reinink** [comment]
Hey thanks @ajnsn! Cool, thanks for this PR. I'll do some testing and see how it works. 👍 

One question, is this a breaking change in any way?

**Comment by ajnsn** [comment]
I've tested it in a current project and did not encounter any changes. Afaik Vue uses `reactive()` under the hood if you init a non-primitive value with `ref()`, so I would not expect any changes.

But I did not test it thoroughly.

**Comment by haikyuu** [comment]
I think it would be a good idea to have integration tests using pingCRM and [playwright](https://playwright.dev/). I'm currently working on a node adapter and I will probably give it a shot after porting ping crm to node & vue.

Integration tests are the way to go since Inertia's definition of works is: that an inertia backend adapter works well with the front-end library and one of its framework adapters.

**Comment by claudiodekker** [comment]
@haikyuu We actually already have a test suite that's ready to go (https://github.com/inertiajs/inertia/pull/395, @reinink just hadn't had the time to review it yet), so I'd recommend using that instead 👍

**Comment by reinink** [comment]
@ajnsn Hey thanks again for this PR, but I think I'm just going to leave things as they are right now, as the current setup works great, and I'd rather not touch it unless there's an obvious benefit. 👍

**Pull request closed without merging**
