### PR TITLE
Add TypeScript typings

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
After sending in inertiajs/inertia-react#15, I started working on the typings for the core itself (which will be exposed by the `inertia-react` typings too).

I know @sebastiandedeyne isn't a maintainer of this repo, but since he has already a lot of  experience with TypeScript maybe he can take a look at this one?

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
@reinink Are you okay with adding this to the repo once the PR is approved?

**Comment by MichaelDeBoey** [comment]
Since I'm importing the default  in inertiajs/inertia-react#15 (see [Line 1](https://github.com/inertiajs/inertia-react/pull/15/files#diff-494415c3af35245ecae73f5d42d8b331R1)), I thought it would be good to add the typings here as well.

**Comment by MichaelDeBoey** [comment]
@sebastiandedeyne Any news/comments on this one?

**Comment by sebastiandedeyne** [comment]
Sorry, these PR's are still on my todo list, I'll get to them soon!

**Comment by MichaelDeBoey** [comment]
No prob, just wanted to ping you 😉

**Pull request merged**
