### PR TITLE
Add typing for progress parameter in createInertiaApp

### PR DESCRIPTION
**Pull request by Kyzegs**

### CODE REVIEW

**Comment by reinink** [comment]
Hey thanks! Would you be able to add this to the other adapters as well? 🙏

https://github.com/inertiajs/inertia/blob/master/packages/vue2/index.d.ts
https://github.com/inertiajs/inertia/blob/master/packages/vue3/index.d.ts

**Comment by Kyzegs** [comment]
I can definitely do that! I'll get to it when I get home.

**Comment by Kyzegs** [comment]
Anything else?

**Comment by jrson83** [comment]
https://next.inertiajs.com/upgrade-guide

> you can disable the default progress indicator by setting the progress property to false:
```js
createInertiaApp({
  progress: false,
  // ...
})
```

It should be:

```ts
progress?: Parameters<typeof Inertia.setupProgress>[0] | boolean
```

**Comment by jrson83** [comment]
Why, this is wrong.

**Comment by Kyzegs** [comment]
I'll make another PR with fixes.

**Comment by reinink** [comment]
@jrson83 Hey! I corrected it after merging as per your recommendation:

https://github.com/inertiajs/inertia/commit/1c59b38851c857ea9901ffe0ff1be1a91b5065d5

As for those other type changes, feel free to PR those! 💪

**Pull request merged**
