### PR TITLE
Add ability to mutate page props

### PR DESCRIPTION
**Pull request by vinnygambiny**
This PR allows mutating the page props with the usePage function.

This is for these situations https://github.com/inertiajs/inertia/discussions/78

You have only to do `usePage().props.valueName = 'newValue'`

### CODE REVIEW

**Comment by punyflash** [comment]
I don't think that should be a thing. Data which loaded the page should be accessible all the time, no matter what. In case you need it to be reactive and changeable - just create a custom reference that was initialized with the prop value.

**Comment by innocenzi** [comment]
@punyflash there are definitely situations where this would be handy (eg. infinite loading), and Inertia should be more flexible about this.

**Comment by pedroborges** [comment]
I'm closing this PR since the main use case discussed here and on #78 is supporting for infinite scrolling. That's already coming to v2.0 soon, as you can see in [Taylor's Laracon keynote](https://www.youtube.com/watch?v=AwWepVU5uWM&t=2845s) 🚀

**Comment by Fuzzyma** [comment]
@pedroborges the usecase for updating data that comes with laravel echo events is still totally valid.
Not being able to change the page props on an event degrades the usafe of events do "hey, i got something new. Please reload".
It is really not a great ux. I feel like since events are a laravel core feature it would be nice to have a better integration path into inertia here.

There are not really any alternatives to solve this in a nice way and they all come with overhead.

**Pull request closed without merging**
