### PR TITLE
No inertia response handler

### PR DESCRIPTION
**Pull request by KABBOUCHI**
Example:

```js
new Vue({
    store,
    render: h =>
        h(InertiaApp, {
            props: {
                initialPage: initialPage,
                resolveComponent: n => import(`@/Pages/${n}`).then(m => m.default),
                noInertiaResponseHandler: ({ status, data, request }) => { 
                    if(status === 200) {
                        window.location.href = request.responseURL;
                    }else if(status === 403) {
                        Inertia.visit('/admin/403');
                    }
                }
            }
        })
}).$mount(app);
```

### CODE REVIEW

**Comment by m1guelpf** [comment]
This would really help for managing redirects to non-Inertia views while still preserving the Modal functionality on exceptions

**Comment by sebastiandedeyne** [comment]
Hmm, I'd rather solve this on the server with https://github.com/inertiajs/inertia-laravel/issues/57

**Comment by reinink** [comment]
Yeah, I agree with @sebastiandedeyne, this is probably better handled server-side. Right now this would mean that the destination would be loaded twice, which isn't great.

A better solution is coming for this. Thanks either way for the contribution!

**Comment by KABBOUCHI** [comment]
Why we can't solve it from both sides? it dosn't solve everything from laravel side. (ex: if website is down)

**Pull request closed without merging**
