### PR TITLE
Updated $page to access $page directly insted of $page.props

### PR DESCRIPTION
**Pull request by FaizAhmadSE**

### CODE REVIEW

**Comment by reinink** [comment]
Hello, thanks for the contribution, but this change has already been made in #245, and not only for the Vue adapter, but for the React and Svelte adapters too. That PR should be merged and tagged within the week. 👍

**Comment by aske-cph** [comment]
I think the examples here should be updated then:
https://inertiajs.com/shared-data

**Comment by reinink** [comment]
@aske-cph It has been...where are you seeing the old behaviour in the docs?

To be clear, the new behaviour is `$page.props`, which might not be very clear from this issue title.

**Comment by aske-cph** [comment]
Ah i thought the header set the complete opposite - reason i am confused is that i don't get a "props" property in 0.3.3 for some reason - if i dump the $page obj flash for example just lies next to Auth, Errors, Jetstream etc..

**Pull request closed without merging**
