### PR TITLE
WIP Add build step for inertia-svelte

### PR DESCRIPTION
**Pull request by christoomey**
This change represents a first step at adding a building step for the
inertia-svelte package, specifically hoping to address #394.

---

I've introduced rollup as that seems to be the common practice in the
svelte world and I believe I have a working build, but frankly I'm solidly
out of my depth here. One concerning aspect is that the built dist/index.js
is 128kB which makes me think I have some things misconfigured. Hoping to
poke a bit more and perhaps solicit some help from folks who know more than
I do, but wanted to share what I have now.

### CODE REVIEW

**Comment by christoomey** [comment]
Small update based on some pointers from folks on twitter to add a rollup plugin to keep peer deps out of built dist/index.js. Down to 20k (8k gzipped) now, but still thinking that's unreasonably high.

**Comment by mariojankovic** [comment]
Hey @christoomey, this looks good but needs additional tuning. Adding stuff as peerDeps requires both the `external` and `globals` flags. I've fixed these and introduced `terser` to uglify the end results and have been able to bring this down to 7kb and 8kb respectfully. Also note that rollup supports `ROLLUP_WATCH` to watch for dev/production envs.

**Comment by christoomey** [comment]
Closing in favor of https://github.com/inertiajs/inertia/pull/531.

**Comment by claudiodekker** [comment]
Thanks for the contribution @christoomey!

**Pull request closed without merging**
