### PR TITLE
Improve visit cancellation

### PR DESCRIPTION
**Pull request by reinink**
This is another take on @bradlc's work in #25.

This approach uses two callbacks (`resolveComponent` and `updatePage`) from the adapters, instead of just one (`setPage`).

This PR also makes some improvements to the loading indicators.

Closes #25

### CODE REVIEW

**Comment by mirago** [comment]
Hey, is there a reason why the progress indicator does not have a timeout anymore?

**Comment by reinink** [comment]
@mirago Simply because I couldn't get it working properly with the page cancellation. When a page is loading, and you click to visit another page, I want the progress bar to start over. This was basically impossible to get working with Nprogress. Honestly, Nprogress is kind of a pain, and it has been updated in over 4 years.

Long term I'll likely expose a way for folks to create their own loading indicators.

**Comment by mirago** [comment]
I see, thanks for taking your time to explain. I just upgraded my project to this latest version and was quite surprised it displays nprogress all the time now :) No worries though, and I agree it would be nice to add some hooks.

**Comment by reinink** [comment]
For what it's worth, I found that with the 100ms delay, it basically always shows in production anyway. This isn't great, since the local experience is different than production experience.

**Comment by reinink** [comment]
@mirago The progress bar delay has been brought back: https://github.com/inertiajs/inertia/commit/fc4775ce33f6e8875b76e11973aedfba209ff476

**Comment by MichaelDeBoey** [comment]
One step closer to ditching the dependency 😉

**Comment by reinink** [comment]
Yup.

**Pull request merged**
