### PR TITLE
Example: Link preloading (GET-only)

### PR DESCRIPTION
**Pull request by claudiodekker**
This functionality adds a 'request manager' of sorts, which has the following behavior:

1) If there is no request, it starts the request and returns a promise that will eventually resolve (or fail)
2) If the request is pending, it hooks a promise-resolver into the existing request, which will resolve (or fail) once completed.
3) If the request has successfully finished, it returns a promise that instantly resolves to the (cached) request.
4) If the prefetch request failed, it'll start a new request (see 1)

In all situations, in addition to the promise, you'll receive a cancel hook, so that if you want to cancel the individual visit.

This request manager has been implemented to pre-load GET requests on-hover (see https://instant.page/ for what it's supposed to do), as well as to cancel all 'pending' requests once the page switches.

Solves #45

### CODE REVIEW

**Comment by ArondeParon** [comment]
Is this still being considered? Sounds like a great improvement!

**Comment by reinink** [comment]
Hey! Thanks so much for your interest in Inertia.js and for submitting this contribution.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this PR is still relevant, and if that's the case feel free to re-submit it. If it's a new feature and not a bug fix maybe respond here first to make sure that it's something we want to include in the library.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Comment by TheBlckbird** [comment]
@claudiodekker I think you could update this PR so it works with the current version of Inertia and re-submit it.

**Comment by TheBlckbird** [comment]
although I would use mousedown and not hover

**Comment by aarondfrancis** [comment]
Any chance we can pick this one back up? I really like Livewire's prefetching, it'd be nice to have it here too

**Comment by reinink** [comment]
> Any chance we can pick this one back up? I really like Livewire's prefetching, it'd be nice to have it here too

It's something we're looking at for v2 👍

**Pull request closed without merging**
