### PR TITLE
feat(vue): Inject Props

### PR DESCRIPTION
**Pull request by KABBOUCHI**
Add option to auto inject props on pages.

```js
// ./app.js
new Vue({
    render: h => h(InertiaApp, {
        props: {
            initialPage: JSON.parse(app.dataset.page),
            resolveComponent: name => require(`./Pages/${name}`).default,
            injectProps: true
        },
    }),
}).$mount(app)
```

image

image

### CODE REVIEW

**Comment by reinink** [comment]
Hey @KABBOUCHI, thanks for the contribution!

So, my gut on this is "no", simply because this doesn't feel like the Vue.js way of doing things. I think it's better to explicitly set props, and I think Vue developers are used to doing it that way.

Do you have any precedent from elsewhere in the Vue community indicating that this is a valid approach?

**Comment by KABBOUCHI** [comment]
Pages are controlled by Inertia, pages are not reusable components, for me it's safe to use and it's optional, it's not forced by default.

**Comment by reinink** [comment]
Yeah, I know...and for that reason it's tempting to merge this in. However, my gut is telling me "no". Vue already has an established way of registering props, and I want to be careful not to introduce new "magical" ways of doing something that is already a "solved thing" in Vue.

In addition to that, this top-level option won't apply to the other adapters (React and Svelte). Not that all adapters need feature parity, but it is another consideration.

I'm going to close this for now, but am (obviously) willing to reconsider in the future if we get this feature request more often.

Thanks again @KABBOUCHI! 🤟

**Comment by KABBOUCHI** [comment]
> In addition to that, this top-level option won't apply to the other adapters (React and Svelte). Not that all adapters need feature parity, but it is another consideration.

but react inject all the props? they already available.

**Comment by reinink** [comment]
> but react inject all the props? they already available.

Correct, which is why the `injectProps` feature wouldn't apply there.

**Pull request closed without merging**
