### PR TITLE
Allow React 18 as a peer dependency

### LINKED ISSUE #1152: Include React 18 as peer dependency
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-react` version: 0.8.0

### Describe the problem:

Inertia works fine with React 18, which is why it should be included as a peer dependency.

Due to the missing peer dependency you get an error every time you do something in npm:

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   dev react@"^18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.9.0 || ^17.0.0" from @inertiajs/inertia-react@0.8.0
npm ERR! node_modules/@inertiajs/inertia-react
npm ERR!   dev @inertiajs/inertia-react@"^0.8.0" from the root project
```

### PR DESCRIPTION
**Pull request by Studio384**
Fixes #1152

### CODE REVIEW

**Comment by reinink** [comment]
@Studio384 Hey thanks for this — have you actually tested it to see if there are any issues?

**Comment by Studio384** [comment]
It will require changes to the documentation under "Client-side Setup" to use React 18 properly with the updated Render API, but beyond that there shouldn't be issues. I've been using React 18 in combination with Inertia since React 18 was released and have yet to run into any issues. There shouldn't be any breaking changes in React 18 that are relevant to Inertia itself and as far as I can tell no deprecations are relevant to Inertia either.

**Comment by rdgout** [comment]
@reinink think this can be merged soon? 
It's been almost 6 months without a release. Also React 18 fully functions in backwards compatibility when not running with the new `createRoot` methods so there should be no issues at all. See https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis for more information.

**Comment by BenSeDev** [comment]
@reinink It would be very helpful if this gets merged. 

🙇

**Comment by ntson** [comment]
> @reinink It would be very helpful if this gets merged.
> 
> 🙇

agree

**Comment by jefsev** [comment]
Guys i made a PR for inertiajs.com : https://github.com/inertiajs/inertiajs.com/pull/243

Please upvote so this can be resolved and we can all stop using npm install --legacy-peer-deps :P

**Comment by reinink** [comment]
@Studio384 — Thanks so much for this. I've merged it in, and will try to get this released tomorrow 👍

**Comment by josebailo** [comment]
Hey @reinink, any idea when will this be released?

**Comment by Yalc99** [comment]
Hey @reinink, will a new version be released soon?

**Comment by reinink** [comment]
Yup — just figuring out stuff around the releases, hope to have this out very soon 👍

**Comment by jaxramus** [comment]
thank you for all your hard work @reinink

**Comment by lavinia-adochitei** [comment]
@reinink When do you expect the release?

**Comment by scajal** [comment]
Bump this.

**Comment by sideshowlol** [comment]
Looking forward to this release. Thank you Jonathan for all your hard work on Inertia. It's amazing!

**Comment by amargoCactus** [comment]
also waiting for the realease

**Comment by W-MasanoriIwakura** [comment]
I am also looking forward to the release

**Comment by bayasgalanpf** [comment]
waiting for this release.

**Comment by suleymanozev** [comment]
waiting

**Comment by kjoedion** [comment]
I'm still waiting as well. Been waiting over 2 months. PR was merged can we get this implemented? React 18 has been out since March. If theres anything I can do to help get this rolled out, please let me know.

**Comment by jordyvanderhaegen** [comment]
For those subscribed to this PR, this has been released in [inertia-react@0.8.1](https://github.com/inertiajs/inertia/releases/tag/inertia-react%400.8.1)

**Pull request merged**
