### PR TITLE
Add svelte typescript

### LINKED ISSUE #992: Convert @inertiajs/inertia-svelte to TypeScript

### PR DESCRIPTION
**Pull request by orblazer**
Hello,

This add typescript support for `@inertiajs/inertia-svelte`.

This fix #992

### CODE REVIEW

**Comment by eslym** [comment]
somehow i feel like make a pull request to `@types` packages is faster than waiting here to merge

**Comment by Levyks** [comment]
any updates on this PR? typescript support is basically the only thing keeping me from embracing inertia rn

**Comment by RVxLab** [comment]
This PR may require a revisit with the release of 1.0.0. I’d love to see this happen, if I can find the time I’m willing to help out.

**Comment by Bravilogy** [comment]
Any updates on this?

**Comment by RVxLab** [comment]
I made a fork and started some work on this, I would appreciate some extra help.

https://github.com/RVxLab/inertia/tree/svelte-ts

**Comment by weavdale** [comment]
Any update on this. Taylor is open to adding a Svelte stack to Breeze, but I would imagine he would want a typescript option also to match the Vue and React versions. https://twitter.com/taylorotwell/status/1650200589563752451?s=61&t=bEYyjS2U88Zjtv67cnhYxw

**Comment by reinink** [comment]
Hey! Thanks so much for your interest in Inertia.js and for submitting this contribution.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this PR is still relevant, and if that's the case feel free to re-submit it. If it's a new feature and not a bug fix maybe respond here first to make sure that it's something we want to include in the library.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Comment by RVxLab** [comment]
Makes total sense, I appreciate your effort into maintenance and I’ve been in a very similar position. 

Considering this MR is quite outdated, I feel this is the best way to go about it.

**Pull request closed without merging**
