### PR TITLE
Add window.sessionStorage check

### PR DESCRIPTION
**Pull request by ninjaparade**
add try catch to init to make sure `window.sessionStorage` is accessible

### CODE REVIEW

**Review by claudiodekker — CHANGES_REQUESTED** [review]
I'm not sure whether we _want to_ support situations where the session storage isn't available, but if @reinink decides to pull this in, I'd like to point out that we would still have to think regarding what to do with `hardVisit`, as it still accesses the sessionStorage directly:

https://github.com/inertiajs/inertia/blob/0e43679e58e16f798e551acf3b694fe399134108/packages/inertia/src/inertia.js#L193-L195

**Comment by ninjaparade** [comment]
The problem I an trying to solve is that, in an iframe of certain browsers, the call to `window.sessionStorage` is not allowed. With the changes I've suggested above, I haven't encountered any other issues.

**Comment by reinink** [comment]
@ninjaparade I am trying to reproduce this issue, but I can't seem to. I've tried in Chrome, Safari and Firefox, and it seems to work in all. What are the conditions needed to cause this?

**Comment by ninjaparade** [comment]
You should see the error if you embed an inertia app in a iframe in Safari, Firefox, ungoogled chrome or Brave. All of them have very strict protection from frames accessing window and cookies.

**Comment by reinink** [comment]
Hey Yaz, would you mind testing out this solution? #222

I've been unable to reproduce this issue, and kind of like this solution, since it avoids adding a try/catch (which could be thrown for other things, in which we don't actually want to catch it.

Thanks!

**Comment by ninjaparade** [comment]
@reinink I'll test it out today and let you know, thanks for the ping 👍

**Comment by reinink** [comment]
This has been fixed in #257. 👍

**Pull request closed without merging**
