### PR TITLE
remove duplicate license

### PR DESCRIPTION
**Pull request by pkboom**

### CODE REVIEW

**Comment by reinink** [comment]
Buddy! Nice to hear from you, and thanks for catching this! 💪

**Comment by reinink** [comment]
Why did you close it? 🤔

**Comment by pkboom** [comment]
Hey, been a while. Heard your eloquent course is a huge success. Congrats, man. My bad. Didn't know it was closed. Always appreciate your work.

**Comment by reinink** [comment]
Thanks buddy! 👍

**Pull request merged**
