### PR TITLE
Replace Promise with async

### PR DESCRIPTION
**Pull request by claudiodekker**
Minor simplification for https://github.com/inertiajs/inertia/pull/116

### CODE REVIEW

**Comment by reinink** [comment]
Love it.

**Comment by reinink** [comment]
One question, will this work with IE11? 😬

**Comment by claudiodekker** [comment]
Oof, yeah, no, it won't. Completely forgot about IE11 🙀🙃

**Comment by reinink** [comment]
I’m seriously considering dropping IE11 support. 🤔

**Comment by pedroborges** [comment]
Microsoft itself is [dropping IE11](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666) support for their services.

**Comment by claudiodekker** [comment]
Yeah, it's worth considering. I was just thinking about asking your thoughts on it as well.

It's a bit of a mixed bag IMO, as Inertia is young & (unfortunately) still small enough to be able to make big decisions like this, but at the same time I can imagine people using it in apps built for institutions where IE is the only option.

Microsoft just announced they're killing support for their own IE11 & Legacy Edge as early as December: https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666

Vue 3 will still be supporting it, but will apparently ship a separate build that has "proxied" support for it built in https://github.com/vuejs/rfcs/issues/183

**Pull request merged**
