### PR TITLE
Remove lock files from .gitignore and add package-lock.json file

### PR DESCRIPTION
**Pull request by lamartire**
Hello, @reinink! I didn't find `lock` files inside this project. It is very bad, because without `lock` files it is very difficult to resolve correct dependency version. Also, it is not secure. [The first discussion about it](https://stackoverflow.com/a/39992365) from search. May be there is any reason to this?

### CODE REVIEW

**Comment by lamartire** [comment]
Of course, I can add `yarn.lock` instead `package-lock.json`

**Comment by MichaelDeBoey** [comment]
I think you shouldn't add them into libraries, only in apps.

**Comment by reinink** [comment]
From my understanding, Yarn and NPM won't use the library lock file. The only benefit to including this would be for library developers to ensure a specific version is being used while building the library, and even that is a debatable topic.

However, as @MichaelDeBoey said, you'll definitely want to use a lock file in your app. 👍

**Comment by lamartire** [comment]
For example, you have library and `axios`'s dependency has security issue. Before `axios` update you can't get different version of vulnerable dependency. I think, it is a good opportunity to solve this moment also on library level, not only in applications.

**Pull request closed without merging**
